# Generated by Django 3.0 on 2019-12-02 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0002_auto_20191202_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rating', models.IntegerField(choices=[(1, 'One Star'), (2, 'Two Stars'), (3, 'Three Stars'), (4, 'Four Stars'), (5, 'Five Stars')])),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='booklist.Book')),
            ],
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'status'},
        ),
        migrations.RemoveField(
            model_name='book',
            name='rating',
        ),
    ]
