# Generated by Django 3.0 on 2019-12-08 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0005_auto_20191208_1339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='status_name',
            new_name='name',
        ),
    ]
