# Generated by Django 3.0 on 2019-12-17 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0007_auto_20191214_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='shelves',
        ),
    ]
