# Generated by Django 3.0 on 2019-12-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0008_remove_book_shelves'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='shelves',
            field=models.ManyToManyField(blank=True, to='booklist.Shelf'),
        ),
    ]
